// Every test file, imported for its side effect of registering tests. Add new test files here.
import './state.test.js'
import './trail.test.js'
import './vfs.test.js'
import './core.test.js'
import './snake.test.js'
import './commands.test.js'
import './matrix.test.js'
import './corruption.test.js'
import './engine.test.js'
import './console.test.js'
